### ISSUE TITLE
Large Repository Clone

### ISSUE THREAD

**Issue by HaroonSaid** [otac0n/WebGitNet#51]
We have a fairly large repository (~8GB) and we cant seem to clone the repo using WebGitNet.
We are running Windows 2008 R2 Server x64 with IIS 7.5, using standard windows authentication.
We have smaller repos that we have no issues cloning.

Please advice what kind of tracing is available or I can turn on to figure out whats the problem.

**Comment by nzbart** [comment]
@otac0n Is there any chance of building a new release with this fix included?
